### ISSUE TITLE
Question/Help: Template is not loaded for Custom Post Types

### ISSUE THREAD

**Issue by hphoeksma** [nk-o/lazy-blocks#101]
I created a dummy test Custom Post Type:
```
function register_custom_post_types() {
	register_post_type('test', [
		'labels' => [
			'name' => __('test'),
		],
		'public' => true,
		'supports' => [
			'title',
			'editor',
			'custom-fields',
		],
		'show_in_rest' => true,
	]);
}
add_action('init', 'register_custom_post_types');
```

Next I added a template for this type and added an image block to it. When creating a new 'test' post nothing happens.
When I do exactly the same for default post / page, it works as expected.
Is there anything special in 'supports' that need to be added?

**Comment by nk-o** [comment]
It just works on my test server with your custom post. Template:

![image](https://user-images.githubusercontent.com/14810891/65412833-b92ef100-ddf8-11e9-8864-1f247ce9a289.png)

New custom post:

![image](https://user-images.githubusercontent.com/14810891/65412794-a61c2100-ddf8-11e9-89b5-b8d5c3e7cf53.png)

**Comment by hphoeksma** [comment]
Okay - weird. Maybe because I run a Multi Site setup here? 
For now I have taken another route and will close this. Thanks for your response.

**Comment by nk-o** [comment]
I have tested it with Multisite also, it is working fine.
