### ISSUE TITLE
Trigger change?

### ISSUE THREAD

**Issue by brownrl** [nk-o/lazy-blocks#105]
Man I have been at this for a while now. Essentially I am trying to make my own full editor control. I know maybe insane however unfortunately I got some folks here who are going to die unless I somehow let them put more "things" in to the content like tables, lists, etc...

I've made a textarea control in a block.

Then I converted that textarea to a tinyMCE wysiwyg editor...

It converts, but it doesn't trigger the necessary change,event to correctly update the field.

this is the JS/jQuery code that I am doing, I've tried just about everything but I have sneaky feeling that you know a trick?

```
$( document ).ready(function() {
    setTimeout(function(){
        $('.components-textarea-control__input').each(function(index){
            var sel = '#' + $(this).attr('id');
            tinymce.init({
                selector: sel,
                setup: function (editor) {
                    $(sel).attr('style', '');
                    editor.on('change', function () {
                        // console.log($(sel));
                        $(sel).val(editor.getContent());
                        $(sel).text(editor.getContent());
                        $(sel).trigger('keydown');
                        $(sel).trigger('keypress');
                        $(sel).trigger('keyup');
                        $(sel).trigger('change');
                        $(sel).trigger('inputText');
                    });
                }
            });
        });
    }, 300);
});
```

I will fine tune better which textareas to convert later, but for now I need to get past the hurdle of firing the correct bits to properly update this and allowed the publish button to be clicked.

Any ideas?

**Comment by nk-o** [comment]
Hey.

I think Gutenberg API may help somehow - https://developer.wordpress.org/block-editor/data/data-core-editor/#updateBlockAttributes

p.s. better to add API in the plugin code, that will let users to add their own controls using React (https://github.com/nk-o/lazy-blocks/issues/63)

**Comment by nk-o** [comment]
API for custom controls will be added to Lazy Blocks v2.0.0

Documentation lazyblocks.com/documentation/examples/create-custom-control
Custom Control Template nk-o/lazy-blocks-custom-control-template
