### ISSUE TITLE
WYSIWYG / rich_text field not displaying in editor

### ISSUE THREAD

**Issue by richthegeek** [nk-o/lazy-blocks#106]
Wordpress 5.2.4
LazyBlocks 1.8.0

I've added a lazy block which contains a few fields including a rich_text field. This has been working for a while but now all it shows is an empty area.

Inspecting Gutenberg's React components, the value is there further up the tree but the WYSIWYG editor is not working.

Full block content is here: https://gist.github.com/richthegeek/5bce4c891f712cc62ebc6008a865e199 - originally the "description" field was rich_text and the "test wysiwyg" field did not exist. That is just for testing. But the issue is the same regardless of field name :)

Visually it looks like this for me:
<img width="406" alt="Screenshot 2019-10-24 at 14 22 53" src="https://user-images.githubusercontent.com/613900/67489623-c6decd00-f669-11e9-86bf-60ee268d4b1c.png">

There are some console warnings that show up for me:
<img width="867" alt="Screenshot 2019-10-24 at 14 23 36" src="https://user-images.githubusercontent.com/613900/67489673-dfe77e00-f669-11e9-90db-a31800ae2817.png">

Any ideas?

**Comment by nk-o** [comment]
Hey.

For me this field is working fine. Checked also after reloading post:

![image](https://user-images.githubusercontent.com/14810891/67850447-74922600-fb19-11e9-8dcc-22c0efc7e986.png)

What about deprecaed warnings in console - it is from the latest Gutenberg version. Will be fixed in the next plugin update.

**Comment by richardvuu** [comment]
Hi, thanks for getting back to me.

The behavior this field changed - firstly the content that was already in there from before was no longer rendering in the rich_text field, so the content seemed lost. And secondly, it seemed visually different. No border and no toolbar? But maybe I'm confusing it with a different rich_text field.

**Comment by nk-o** [comment]
Yes, visual part was changed by Gutenberg code and styles, but I'm not sure it somehow changed output content.
