### ISSUE TITLE
Choose custom image size in control-type image

### ISSUE THREAD

**Issue by neppers2** [nk-o/lazy-blocks#113]
Is there any possibilities to choose what image size to show in the content? 

Ex:
`<img src="<?php echo esc_url( $attributes['image']['url']['medium'] ); ?>">
`

**Comment by rawsta** [comment]
Have you tried this:
```
<?php
$image = get_lzb_meta( 'control_meta_name' );
echo wp_get_attachment_image( $image['id'], 'large');
```

**Comment by nk-o** [comment]
Added example here - https://lazyblocks.com/documentation/blocks-controls/image/

**Comment by neppers2** [comment]
If I use that code i get this output, I would like to return only the url of the spesific image f.ex "https://www.domain.net/wp-content/uploads/2020/03/photo-1542308721550-1055693ff852-1920x1280.jpg" :

<img width="1920" height="1280" src="https://www.domain.net/wp-content/uploads/2020/03/photo-1542308721550-1055693ff852-1920x1280.jpg" class="attachment-topimage_1920px size-topimage_1920px" alt="" srcset="https://www.domain.net/wp-content/uploads/2020/03/photo-1542308721550-1055693ff852-1920x1280.jpg 1920w, https://www.domain.net/wp-content/uploads/2020/03/photo-1542308721550-1055693ff852-300x200.jpg 300w, https://www.domain.net/wp-content/uploads/2020/03/photo-1542308721550-1055693ff852-1024x683.jpg 1024w, https://www.domain.net/wp-content/uploads/2020/03/photo-1542308721550-1055693ff852-768x512.jpg 768w, https://www.domain.net/wp-content/uploads/2020/03/photo-1542308721550-1055693ff852-1536x1024.jpg 1536w, https://www.domain.net/wp-content/uploads/2020/03/photo-1542308721550-1055693ff852-2048x1365.jpg 2048w, https://www.domain.net/wp-content/uploads/2020/03/photo-1542308721550-1055693ff852-720x480.jpg 720w, https://www.domain.net/wp-content/uploads/2020/03/photo-1542308721550-1055693ff852-510x340.jpg 510w, https://www.domain.net/wp-content/uploads/2020/03/photo-1542308721550-1055693ff852-433x288.jpg 433w, https://www.domain.net/wp-content/uploads/2020/03/photo-1542308721550-1055693ff852-523x348.jpg 523w, https://www.domain.net/wp-content/uploads/2020/03/photo-1542308721550-1055693ff852-540x360.jpg 540w, https://www.domain.net/wp-content/uploads/2020/03/photo-1542308721550-1055693ff852-696x464.jpg 696w, https://www.domain.net/wp-content/uploads/2020/03/photo-1542308721550-1055693ff852-831x554.jpg 831w" sizes="(max-width: 1920px) 100vw, 1920px">
