### ISSUE TITLE
Can I add a color picker to a LazyBlock text field

### ISSUE THREAD

**Issue by celliGit** [nk-o/lazy-blocks#115]
Trying to add a color control to a lazyBlock text field that I created, so that the person working in the wp admin can control the color and text size of each of the text fields. Is there an example somewhere how to build this ?

**Comment by nk-o** [comment]
I don't quite understand what do you want to achieve...

**Comment by celliGit** [comment]
Thanks for the reply. Sorry, I didn't realize that I could add a variable to inline styles to attach the color picker to an elements property like this:
<div class="bkgContainer" style="background-color:{{bkgcol}}">

LazyBlocks working great!
