### ISSUE TITLE
Store values in Metafield unserialization issue

### ISSUE THREAD

**Issue by mainpart** [nk-o/lazy-blocks#117]
I found strange behavior of LazyBlock - when i'm storing value in post meta i need explicitly set up meta field name equal to block name in order to make this code works:

`
    if ( $fix_meta_value ) {
        $result = json_decode( urldecode( $result ), true );
    }
`

It works only when 
![image](https://user-images.githubusercontent.com/2713266/73905033-93e6df00-48d0-11ea-9def-991d81ec0d9d.png)
is equal to 
![image](https://user-images.githubusercontent.com/2713266/73905071-b7118e80-48d0-11ea-8bf7-6100dae918d8.png)

not sure if it's intended behavior since meta name is optional and default placeholder is same as name. Maybe lazyblock should store post metafields already decoded in json format, or even in plain array format since `update_post_meta` supports (de-)serialization on the fly.

**Comment by nk-o** [comment]
Is it still don't work properly in v2.0.1? Please, attach your block JSON (https://lazyblocks.com/documentation/export-blocks/#export-json-from-blocks-list), so I can import it and see the bug locally.

**Comment by mainpart** [comment]
Sorry, i've downloaded version from wordpress.org and it is 1.8.2
I'll update and return here

**Comment by mainpart** [comment]
seems to be i've downloaded it somewhere else. official is 2.0.1
i'm closing this
