### ISSUE TITLE
Cyrillic letters not works in categories

### ISSUE THREAD

**Issue by mainpart** [nk-o/lazy-blocks#118]
Cyrilic letters are not saving in categories:
![image](https://user-images.githubusercontent.com/2713266/73912359-e632fa80-48e6-11ea-896d-78432bea77fc.png)

I see empty variable `category` in network tab passed to `/wp-json/lazy-blocks/v1/update-block-data/?_locale=user` 

when category is in english i can see something like slug passed to the backend.

**Comment by nk-o** [comment]
Tested, but works fine for me:

1. ![image](https://user-images.githubusercontent.com/14810891/74374933-70e88d80-4df0-11ea-9bba-ff3646fd2475.png)
2. ![image](https://user-images.githubusercontent.com/14810891/74374974-8a89d500-4df0-11ea-9b00-3fe1026610ab.png)
3. ![image](https://user-images.githubusercontent.com/14810891/74374993-9c6b7800-4df0-11ea-8b9d-a9bb83382315.png)
