### ISSUE TITLE
Empty Classic Editor in multiple Blocks

### ISSUE THREAD

**Issue by kooolloook** [nk-o/lazy-blocks#119]
First of all: thank you for your plugin and the update.

Almost everything works. I have a problem with the Classic Editor. If this is integrated into a block and I embed it several times on one page, the first Classic Editor is displayed - but the following ones are not. Multiple is checked.

Have to pay attention to anything else?

Addendum: If I change the control in Rich Text - these will appear. 

WP: 5.3.2 
Lazy Blocks: 2.0.1

**Comment by kooolloook** [comment]
I created a simple block and integrated it twice on one page. In the lower block you can see that the Classic Editor is not displayed. Any Ideas?

![Screenshot](https://user-images.githubusercontent.com/54644297/74447907-5d820480-4e7a-11ea-9804-37dd2ae4b33f.png)

**Comment by hakanxemik** [comment]
I have the same issue. Unfortunately I couldn't find anything either but it has to do with the control id of the block. If you inspect the block element you will see that it has the same ID.

![image](https://user-images.githubusercontent.com/47503046/74855699-54dd7280-5341-11ea-80eb-a623c9f548cb.png)

Would be great if anyone could solve this issue/bug.

**Comment by hakanxemik** [comment]
I have the same issue... 

After inserting the same lazyblock the second classic editor  is always blocked (like in the second comment).

Unfortunately I couldn't find any solutions, but I think it has to do something with the block id. If you look at my screenshot, you can see that the classic editors have the same id and that the second one doesn't get initialized (JavaScript bug?).

![image](https://user-images.githubusercontent.com/47503046/74923471-2313ec80-53d1-11ea-819e-6dde806e7ee1.png)

Would appreciate it, if anyone could help us or solve this problem :)

**Comment by nk-o** [comment]
Thank you for reporting to me, it will be fixed soon 🥳

**Comment by hakanxemik** [comment]
I found a bugfix/workaround which works for me now. I added a randomized number to  the editorId  in controls/classic_editor/script.jsx and the editor is working again. Looks like this:


`editorId={ `${ props.uniqueId }${ ( new Date().valueOf() ) }` }`
