### ISSUE TITLE
WordPress 5.4 breaks editor UI

### ISSUE THREAD

**Issue by nikkoa** [nk-o/lazy-blocks#132]
Seems like the updates to the gutenberg editor on WordPress 5.4 breaks the UI. They did get rid of the need for negative margins according to the release notes, so I believe that's the cause.

<img width="1380" alt="Screen Shot 2020-04-03 at 9 31 35 PM" src="https://user-images.githubusercontent.com/25129574/78366089-9759c680-75f2-11ea-9dc1-7c5e2c14b32b.png">

**Comment by TezlaX** [comment]
Yep, I also noticed, that the 'align' classes are no longer applied to the blocks, since WP 5.4 got rid of some wrapper divs. Affects the block editor only though, frontend looks good to me so far.

**Comment by nk-o** [comment]
Thank you for contribution. WP 5.4 compatibility added here - https://github.com/nk-o/lazy-blocks/commit/4b9fea0d6f72c95c4f775d9b739700e1d199453a
