### ISSUE TITLE
Multiple block instances into single code?

### ISSUE THREAD

**Issue by gettonet** [nk-o/lazy-blocks#134]
Hi,

I'm trying to use simple block as anchor, so there can be multiple anchors in different positions on the page.
My idea is to render a menu from all anchors, but I'm not sure where to start.

Is there a (php) way to get all instances of a block on a page and then use foreach loop to put all their data in single block of code? And, since those are anchors, item order in my menu must be exactly like anchors appear on the page..
Many thanks in advance.

**Comment by nk-o** [comment]
Hi.

This is not related to the Lazy Blocks plugin directly. This is Gutenberg-related question. This article will be helpful - https://www.billerickson.net/access-gutenberg-block-data/

Regards, nK.

**Comment by gettonet** [comment]
Beautiful. Thank you for your guidance, that link is really helpful!
