### ISSUE TITLE
Update code does not work

### ISSUE THREAD

**Issue by fif10** [nk-o/lazy-blocks#141]
Hello 

First of all thank you for this wonderful plugin ! 

The update of the code (frontend, editor and other fields) is not working for me. (initial saving is ok)
The 'Post updated' notification is shown, but if I refresh the frontend code value is still the previous one
If I update directly in the custom field part, it works.
I tried with version 2.0.7 (also tried to rollback to 2.0.4 and same issue) 
Tried with firefox and chrome. 
wordpress v5.4.1

Sorry if this issue is a duplicate. :-s
Thanks

**Comment by nikkoa** [comment]
I'm not sure if this is the same root cause as @fif10's, When saving the block definition, I also get a "Post updated" notification but I'm getting an error 403 (Unauthorized) (POST request via XHR to /wp-json/lazy-blocks/v1/update-block-data/ ). When I check via inspector, the error seems to be issued by CloudFlare (as the domain itself goes through the CDN). However, saving the actual pages that use the blocks works with no issues, so I'm not sure it's primarily due to the CDN. Invalid auth tokens, cookies, or headers perhaps?

Happens on both 2.0.4 and 2.0.7, and WordPress 5.4.1 as well. Tried on both Chrome and Safari. No other plugins installed. Let me know if I can provide more info.

Thank you!

**Comment by fif10** [comment]
Ok, some progress .... 
It works if I deactivate ghostkit. any version incompatibility ?

**Comment by nk-o** [comment]
@fif10 could you export JSON of your block, that is not saving? https://lazyblocks.com/documentation/export-blocks/  
  
Attach it here in reply, I'll check it.  
  
@nikkoa not sure it is a plugin-related issue. We use the default rest-api functionality with AJAX requests.

**Comment by fif10** [comment]
Yes. 

Step to reproduce : 
- have Ghost Kit (v.2.12.5) and lazy blocks installed and activated 
- create a new lazy block. (see export). here I set only the code, and single output 
![image](https://user-images.githubusercontent.com/5849803/82784981-f8b74c80-9e61-11ea-8dcb-c4d1ce290118.png)
- publish => it is saved
- refresh page and change code 
![image](https://user-images.githubusercontent.com/5849803/82785025-14baee00-9e62-11ea-9986-835b78d2bf96.png)
- Update 
- refresh and you see  =>  it was not saved. 
- deactivate ghost kit, refresh, update code, and update => it is saved

- The block json
`[
    {
        "id": 1824,
        "title": "",
        "icon": "<svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" xmlns=\"http:\/\/www.w3.org\/2000\/svg\">\n<rect opacity=\"0.25\" width=\"15\" height=\"15\" rx=\"4\" transform=\"matrix(-1 0 0 1 22 7)\" fill=\"currentColor\" \/>\n<rect width=\"15\" height=\"15\" rx=\"4\" transform=\"matrix(-1 0 0 1 17 2)\" fill=\"currentColor\" \/>\n<\/svg>\n",
        "keywords": [],
        "slug": "lazyblock\/no-slug",
        "description": "",
        "category": "common",
        "category_label": "common",
        "supports": {
            "customClassName": true,
            "anchor": false,
            "align": [
                "wide",
                "full"
            ],
            "html": false,
            "multiple": true,
            "inserter": true
        },
        "ghostkit": {
            "supports": {
                "spacings": false,
                "display": false,
                "scrollReveal": false
            }
        },
        "controls": [],
        "code": {
            "editor_html": "",
            "editor_callback": "",
            "editor_css": "",
            "frontend_html": "<h1> block updated <\/h1>",
            "frontend_callback": "",
            "frontend_css": "",
            "show_preview": "always",
            "single_output": true,
            "use_php": false
        },
        "condition": []
    }
]`

**Comment by nk-o** [comment]
Hey.

I can't repeat the problem. It always updates with no problems (with and without Ghost Kit) 🤷‍♂️

**Comment by fif10** [comment]
Hi 

Thanks a lot for your help 
I figure out that was the ghost kit custom fields that made it fail.
I finally fixed it by deacrtivating only this

![image](https://user-images.githubusercontent.com/5849803/83871778-fe017a80-a730-11ea-8b5a-222b5e78783f.png)
![image](https://user-images.githubusercontent.com/5849803/83871768-f93cc680-a730-11ea-82e2-27525a20e9db.png)

I don't close myself (up to you :-)) it in case you want to fix it. 
Thanks for all.
