### ISSUE TITLE
Updating select control's choice values does not update existing blocks in pages/posts

### ISSUE THREAD

**Issue by martynbiz** [nk-o/lazy-blocks#143]
I don't know if this is a bug, or intended behaviour. If the latter, I guess this might be a feature request:

If I create a select control with some choices. Then I use my new block on a page, and choose one of the select choices. Now I have a page block instance on that page. Then, if I change the choice value in the lazy blocks block editor, the page block instance does not update. I think this would be problematic if I had 100 instances of this block.

If this is the intended behaviour, then maybe this would be a useful feature to have instead or in addition to the existing select control. Even if you could have re-usable lists that could be linked to the select control as choices.

**Comment by nk-o** [comment]
Hey.

What exactly is expected to change? If you update the list of choices in select control, it will be updated in all your existing blocks on the page.

But the value, selected in the block and saved in the post, will not be changed automatically. It is already stored in post content, we can't control it.
