### ISSUE TITLE
Use of undefined constant selected - assumed 'selected'

### ISSUE THREAD

**Issue by gettonet** [nk-o/lazy-blocks#145]
PHP Warning:  Use of undefined constant selected - assumed 'selected' (this will throw an Error in a future version of PHP) in /wp-content/plugins/lazy-blocks/classes/class-blocks.php(1160) : eval()'d code on line 14

Is it only me or is this an issue?

**Comment by nk-o** [comment]
Hi.

Are you trying to output the undefined 'selected' option in your custom block code?

Export your block to JSON and attach it in reply, so I will be able to look at your block locally. https://lazyblocks.com/documentation/export-blocks/

**Comment by gettonet** [comment]
Thank for your reply.
I have to say your plugin is the best thing that happened since Gutenberg arrived, period. Thank you for your work.
I have several blocks, is this error caused by some of my block code? I thought it was from the plugin itself...
Here's JSON from all the blocks (change the extrension, since JSON file's not allowed to attach here):
[lzb-export-blocks-2020-05-30.txt](https://github.com/nk-o/lazy-blocks/files/4705649/lzb-export-blocks-2020-05-30.txt)

**Comment by gettonet** [comment]
It was in my code, indeed. Forgot to put '' on my echo.
