### ISSUE TITLE
Allow multiple inner blocks on a single block

### ISSUE THREAD

**Issue by martynbiz** [nk-o/lazy-blocks#146]
I want to use inner blocks to acheive a two/three Bootstrap column layout using inner blocks. For example:

Fields: maincolumn (inner block), sidebar (inner block)

```
<div class="container">
    <div class="row">
        <div class="col-sm-8">
            {{maincolumn}}
        </div>
        <div class="col-sm-4">
            {{sidebar}}
        </div>
    </div>
</div>
```

However, it seems when I've added one inner block, it's disabled when I try to add another. Can this feature be requested? Or is there a reason for not allowing multiple inner blocks?

**Comment by nk-o** [comment]
Unfortunately, it is not possible to output multiple InnterBlocks components in Gutenberg blocks. #103
