### ISSUE TITLE
How do I get the render output programatically?

### ISSUE THREAD

**Issue by plueschpruem** [nk-o/lazy-blocks#147]
Lazy Blocks works for me, but I have a little headache on how to retrieve the block output via AJAX.

Right now I get the post data like this in my DB connector:
`$post = get_post($_POST['id']);`
For WP included blocks that gives me a `$post->post_content` with the usual  markup and then the rendered content - like this:
```
<!-- wp:heading -->
<h2>Adventures</h2>
<!-- /wp:heading -->
```
Lazy Blocks only returns the  part with the $attributes, no matter what the Frontend / Editor code is.

For a simple Text Element I get:
```
<!-- wp:lazyblock/text-test {"test1":"ydfsdfsdfsdfsdfsdf","blockId":"2b1Fs5","blockUniqueClass":"lazyblock-text-test-2b1Fs5"} /-->
<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->
```
whereas visiting that post via "preview post…"  shows the correct template results.

**Comment by nk-o** [comment]
Render blocks using this function - https://developer.wordpress.org/reference/functions/render_block/

**Comment by plueschpruem** [comment]
Ah alright, it's a WP function that I must use…
Thanks dude!
