### ISSUE TITLE
Conditionally load stylesheets and scripts if a block is used

### ISSUE THREAD

**Issue by martynbiz** [nk-o/lazy-blocks#148]
I have a block that outputs a list of results. I have a script that this block needs to enable the filters for that list of results using JavaScript. I want to enqueue this script only if this block is used. It would be good if there was an option to enqueue scripts and/or stylehsheets per block.

**Comment by gettonet** [comment]
I do it like this:

`if (has_block( 'lazyblock/your-block-slug' )) { 
   $script = '...';
    wp_enqueue_script( 'your-script-file', get_template_directory_uri() . '/js/your-script-file.js' ); //add your script
    wp_add_inline_script('timeline', $script, 'after'); //add your inline script, if needed
    }`

Same for stylesheets and whatever you need.

**Comment by martynbiz** [comment]
Yeh I done something similar, thanks.. although your code is a bit tidier :) I just thought it might be a nice addition to the block edit UI without having to go into the PHP.
