### ISSUE TITLE
Block CSS & JS - Component system

### ISSUE THREAD

**Issue by TheALuminium** [nk-o/lazy-blocks#149]
Hi LazyBlocks team,
many thanks for your plugin. It saved me a lot of time and that PHP callback is just awesome.

I have just one question - is it possible to add CSS and JS files into the block? I want to create blocks as components, for example if I build **Tabs** block. I will create a block in admin. Then I will create folder for it in my theme. The folder structure could be like this:

```
─── my-theme/blocks
    ├── tabs
    │   ├── assets
    │   │   ├── lzb-tabs.js
    │   │   └── lzb-tabs.css
    │   └── lzb-tabs.php
```
So in lzb-tabs.php I will have PHP callback and my HTML for the Tabs. But if I want to add assets (lzb-tabs.js, lzb-tabs.css) via **wp_enqueue_style** it is not working and that's a real shame. Because if you will have a lot of blocks you can save a lot of CSS & JS code if you load them together with the block always where the given block is added - specific page/post. And as a result, assets are not loaded on other pages/posts (where the Tabs block is not added) - that would be amazing.

Is there any way to achieve this with your plugin?

Thank you very much for your time
With Regards
Adam

**Comment by nk-o** [comment]
Hi Adam.

Currently, it is not possible with the plugin. But you can do it manually for every Gutenberg blocks. See here code example - https://wordpress.stackexchange.com/questions/328536/load-css-javascript-in-frontend-conditionally-if-block-is-used

Regards, nK.

**Comment by TheALuminium** [comment]
Great, thanks for the clue.

And again, thanks for your work, great plugin.
