### ISSUE TITLE
URL control (probably Gutenberg issue)

### ISSUE THREAD

**Issue by gettonet** [nk-o/lazy-blocks#150]
I know that default Gutenberg component is used for URL input, but I was wondering if internal urls could be stored in different format (plain)?
The issue is, when website domain is changed or when post slug is changed, links become broken.

I suppose that solution could be to use relative links in plain format (which, ideally, would be rendered by permalink rules).

Hope I'm clear :)

**Comment by nk-o** [comment]
Hey.

Nope, it is not possible, as it is the default Gutenberg component, which we can't change. You can use a simple Text control instead.
