### ISSUE TITLE
Obtaining array or object of Inner Block?

### ISSUE THREAD

**Issue by plueschpruem** [nk-o/lazy-blocks#151]
I want to use Inner blocks to render different views of the same blocks.

So I have
#1 an outer block that accepts inner blocks (ultimately I want to have several outer blocks with the same type inner blocks)
#2 an inner block / item of which multiple instances will be added to #1

How do I now return the raw $attributes from #2 to #1 so I can use those in a render loop without resorting to dirty tricks like JSON encoding, etc?

**Comment by nk-o** [comment]
Hi.  
  
I think you can only parse inner blocks manually using function [`parse_blocks()`](https://developer.wordpress.org/reference/functions/parse_blocks/)

**Comment by plueschpruem** [comment]
Cool! That looks like it could do what I need!
Thank you.
