### ISSUE TITLE
Installing the cloudinary app destroys special characters

### ISSUE THREAD

**Issue by pixeldesignstudio** [nk-o/lazy-blocks#153]
Hi,

if the **cloudinary plugin** is installed, it converts all special characters into HTML entities.

### Before saving:
![image](https://user-images.githubusercontent.com/9533914/85957061-663b2900-b98a-11ea-8f16-6f6dc0ebedee.png)

### After saving:
![image](https://user-images.githubusercontent.com/9533914/85957074-80750700-b98a-11ea-9f38-bc0491879e02.png)

Maybe the cloudinary plugin must be blamed, not sure, sorry.

**Comment by nk-o** [comment]
Why the hell this plugin changes our meta data... I think it is their problem.
