### ISSUE TITLE
Select with dynamic options

### ISSUE THREAD

**Issue by pixeldesignstudio** [nk-o/lazy-blocks#155]
Hi, 

how is it possible, to give the editor a category select box.
So a dropdown is visible with all post categories. 
I tried the filter my_lzb_controls_categories but I didn't understand the procedure.

Thanks

**Comment by nk-o** [comment]
Hey.  
  
We don't have such a possibility yet.  
  
If you want to create your own control, you will need to use React and our built-in filters, such as https://lazyblocks.com/documentation/js-filters/lzb-editor-control-render/  
  
Related issue: #8  
  
Regards, nK.
