### ISSUE TITLE
Lazyblocks is not properly sending rendered html

### ISSUE THREAD

**Issue by brownrl** [nk-o/lazy-blocks#157]
I have been in formed by the maintainer of the SEO Framework Plugin that this plugin, Lazyblocks is a step backwards in what is considered wordpress development (I think he's on drugs...)

https://wordpress.org/plugins/autodescription/

He is claiming that Lazyblocks when you do a:

```wp.data.select('core/editor').getEditedPostAttribute('content')```

That readable/parseable HTML should be returned and not the JSON information of the LazyBlocks.

His claim is LazyBlocks is not adhering to the agreed upon modern wordpress way of moving away from shortcodes, pseudo code, json, etc in the content editor.

I don't agree with this 100%, However, many plugins do call this method and do parse or expect parseable HTML to be there.

Yoast SEO as example uses this to do ananlysis on the content of the page for SEO purposes.

Is there a way with Lazyblocks to have the rendered HTML and not have the JSON coding?

I am raising this as a "Possible" issue in that there is some merit to the argument, however I don't fully agree with it in that a plugin the analyses the content of a webpage should in my opinion do so on the actual rendered output/final url and not on some javascript editor pseudo code.

**Comment by nk-o** [comment]
Hey.

Our plugin works with Dynamic blocks only. `wp.data.select('core/editor').getEditedPostAttribute('content')` call returns only static content of the blocks.

If you add `Latest Posts` core block (this is also Dynamic block) to your content, you will also see, that your SEO plugin is not working properly with it.

I will close your issue, as it is duplicate - #95 

Regards, nK.
