### ISSUE TITLE
Changes in the main page URL are not reflected in the attachment's URL

### ISSUE THREAD

**Issue by plueschpruem** [nk-o/lazy-blocks#164]
I use an image input, get the URL with `$attributes["image-1"]["url"]` and all is well.
Until you take your layout page and put it on the live server.
Already existing blocks output the old URL.

To prevent that, I use `wp_get_attachment_url($attributes["image-1"]["id"])` or maybe even some function that returns a scaled image, but I wonder if this is the intended behaviour?

Wouldn't it be more reliable to have the block always re-calculate the URL based on the ID?

**Comment by nk-o** [comment]
URL is saved in the page content. You moved this content to another site and wanted that we change this URL automatically?

Place the image in your content (not using our plugin) and copy it to another site. Will it update automatically? I think nope.

**Comment by plueschpruem** [comment]
Ah OK, I thought Lazyblocks would evaluate the block's attributes during runtime before handing them to the render function.
Thanks for the answer!
