### ISSUE TITLE
"Align" attributeof my blocks buggy. Same values repeating.

### ISSUE THREAD

**Issue by enriquemorenotent** [nk-o/lazy-blocks#165]
When I try to set the "align" options of my block, there seems to be a buggy behaviour. The same values are appearing over and over again, to the point where it gets ridiculously long.

Wordpress version: 5.4.2
Lazy Blocks version: 2.0.10

![image](https://user-images.githubusercontent.com/368842/93778589-5b5d0100-fc26-11ea-840b-96d682406401.png)

**Comment by nk-o** [comment]
@enriquemorenotent the latest plugin version is 2.1.1 

Update your WordPress and then our plugin and let me know if this issue still exists.
