### ISSUE TITLE
custom block theme template method  from  plugin directory

### ISSUE THREAD

**Issue by thunderjet12** [nk-o/lazy-blocks#168]
Hi

how can i point my custom block  to the template file located in plugin or mu-plugin /blocks  folder instead of the active theme / blocks  folder 

regards

**Comment by nk-o** [comment]
Hey.

In the next plugin update you will be able to use these 2 filters:

*   https://lazyblocks.com/documentation/php-filters/lzb-block_render-include_template/
*   https://lazyblocks.com/documentation/php-filters/lzb-block_render-template_exists/

**Comment by thunderjet12** [comment]
aha, that awesome thanks a lot.
Keep Up The Good Work  ^_^

**Comment by janwidmer** [comment]
aaah perfect, now it works, using the full absolute server path I did not try before.. thanks for helping.
