### ISSUE TITLE
Can I import a block via PHP?

### ISSUE THREAD

**Issue by pixeldesignstudio** [nk-o/lazy-blocks#177]
### Issue description:
Is it possible to include a Block in a template file? I even tried a do_shortcode. It's for the search page.

### Lazy Blocks Version:
latest

### WordPress Version:
latest

**Comment by pixeldesignstudio** [comment]
I've found the page:

https://lazyblocks.com/documentation/examples/include-lazy-blocks-within-theme-or-plugin/

But to be honest, I don't understand it. Can someone please explain it to me?

**Comment by nk-o** [comment]
Hey.  
  
If you looking for something like `do_shortcode`, WordPress has the same function for blocks - https://developer.wordpress.org/reference/functions/do_blocks/  
  
This code should work:  
  
```php
<?php  
  
echo do_blocks( '<!-- wp:paragraph --><p>This is Core paragraph block</p><!-- /wp:paragraph -->' );  
```

**Comment by pixeldesignstudio** [comment]
> Hey.
> 
> If you looking for something like `do_shortcode`, WordPress has the same function for blocks - https://developer.wordpress.org/reference/functions/do_blocks/
> 
> This code should work:
> 
> ```
> <?php  
>   
> echo do_blocks( '<p>This is Core paragraph block</p>' );  
> ```

Yes correct!
Something like: 
`<?php echo do_blocks( '<!-- wp:lazyblock/hero-big --><!-- /wp:lazyblock/hero-big -->' );  ?>`

Is this possible yet?

**Comment by nk-o** [comment]
Yes, it is possible, just see how the block outputs in the page code editor and use this code.

![](https://user-images.githubusercontent.com/14810891/99155166-8fa0eb00-26c6-11eb-9fcd-07b9ad8f675d.png)

**Comment by pixeldesignstudio** [comment]
Gosh, sorry, now I get it! 
I have been stuck in the lazyblocks creating page.

**For someone else this stubborn** :laughing: 
You have to insert the block onto a new page, copy it via CMD + C and insert it via do_block `echo do_blocks('')`.

Thx!!!!
