### ISSUE TITLE
Classic Editor Broke on upgrade to 5.6

### ISSUE THREAD

**Issue by brownrl** [nk-o/lazy-blocks#182]
### Issue description:

When you upgrade a site to 5.6 then edit a page/post any classic editor controls no longer render.

### Lazy Blocks Version:

latest 2.2, 2.1.1

### WordPress Version:

5.6

<img width="658" alt="Screen Shot 2020-12-16 at 2 30 10 PM" src="https://user-images.githubusercontent.com/3533399/102354690-379e2280-3fab-11eb-9fd4-65829794a952.png">

### Any helpful information to reproduce the issue (screenshots, code parts)

Normal Classic Paragraph Blocks do work. 

If I downgrade WP core 5.5.3 or 5.5.1 it all comes back fine. 

If you switch from visual editor to code editor and back to visual editor it will render fine.

<img width="409" alt="Screen Shot 2020-12-16 at 2 31 36 PM" src="https://user-images.githubusercontent.com/3533399/102354874-6ddba200-3fab-11eb-8e40-1fa1d1860f10.png">

If you switch the block to edit HTML back to edit Visually it will work fine.

<img width="411" alt="Screen Shot 2020-12-16 at 2 32 07 PM" src="https://user-images.githubusercontent.com/3533399/102354938-7e8c1800-3fab-11eb-8c95-ed33782abe06.png">

On a fresh install of Wordpress 5.6 out of the box and lazy blocks it seems to be ok.

### My Guess

my guess is that with 5.6 the order in which some JS is run has changed. The instantiation of the tinyMCE is no longer working or some "ready" state event is no longer sent so the a trigger doesn't trigger.

**Comment by brownrl** [comment]
If I rollback the core to 5.5.3 it works...

<img width="803" alt="Screen Shot 2020-12-16 at 2 54 55 PM" src="https://user-images.githubusercontent.com/3533399/102357879-1ccdad00-3faf-11eb-9b16-ec92369590f2.png">

**Comment by brownrl** [comment]
If I do this:

```
jQuery( document ).ready(function() {
    setTimeout(function(){
      
      wp.data.dispatch( 'core/edit-post' ).switchEditorMode( 'text' );
      wp.data.dispatch( 'core/edit-post' ).switchEditorMode( 'visual' );

    }, 5000);
});
```

The tinyMCE and editor works. ... after 5 seconds. ;) Not that this is a fix but maybe some insight to the problem.

**Comment by rozanov-lev** [comment]
I'll join you. Same problem on WP 5.6

**Comment by qige33** [comment]
Same problem with me

**Comment by brownrl** [comment]
I am starting to see it is also broken on new installs as well.

**Comment by brownrl** [comment]
When adding a page the classic editor controls are ok. When editing a page no.

**Comment by shanebrightbulb** [comment]
Any potential fix for this incoming?

**Comment by brownrl** [comment]
well I think it is actually a double ended problem. WP.org for sure broke something with 5.6 whether they revert or document the new change is one half. The other will be how or if nK responds either waiting for wp.org or updating lzb. For now the band aid fix above is doing the trick. I lowered the time out to 2 seconds and it's practically unnoticeable.

**Comment by brownrl** [comment]
Ok so I guess it's closed now. So glad it's working and fixed... <not>
