### ISSUE TITLE
Checkbox/toggle control values not returned correctly in get_lzb_meta

### ISSUE THREAD

**Issue by edwinwills** [nk-o/lazy-blocks#185]
### Issue description:
This is my first time using Lazy Blocks (and it's been a while since I've worked with Wordpress), so apologies if I've missed something obvious here, but I'm getting a bit of an odd issue when I try to use checkboxes/toggles and include their value in a template I'm building - I can't get `get_lzb_meta` to return the correct checked/unchecked value of a toggle or checkbox. Instead, it seems to return the value of the set up option (should the control be checked/toggled by default).

### Lazy Blocks Version:
2.3.0

### WordPress Version:
5.6

### Any helpful information to reproduce the issue (screenshots, code parts)
To reproduce:

![Screenshot 2021-01-23 at 13 57 24](https://user-images.githubusercontent.com/550454/105580395-096aea00-5d84-11eb-96ce-4845bec0a2b5.png)
I create a new field "show-down-arrow" as a toggle. I make sure I've checked to include this in Meta. I then use the block on a page, and set the value to checked/toggled.

When I try to inspect the value in PHP in a template file, e.g.

```php
if (get_lzb_meta( 'show-down-arrow' )) {
    echo "TRUE";
} else {
    echo "FALSE";
}
```

I always get the value of $control['checked'] returned, which seems to just be what the default value of the control should be.

I tried to do some debugging, and it looks like the `filter_get_lzb_meta_default` function in `controls/toggle/index.php` is returning the wrong result, specifically:

```php
if ( ! isset( $result ) || ! is_bool( $result ) ) {
    $result = 'true' === $control['checked'];
}
```

As far as I can tell, this should be checking whether `$result` is either blank (unchecked) or `'1'` (checked). Checking the `$control['checked']` seems like it's just checking whether the toggle should be "toggled" by default:

![Screenshot 2021-01-23 at 14 05 05](https://user-images.githubusercontent.com/550454/105580391-053ecc80-5d84-11eb-86db-f4e7567a06c1.png)

I'm happy to have a go at writing a PR if this looks like a bug from your end as well. Thanks

**Comment by nk-o** [comment]
Hey.

If I understand correctly, post meta is not saved properly? Maybe these issues related to yours?

1.  #137
2.  WordPress/gutenberg#23078

Please, check it and let me know helped it or not

**Comment by edwinwills** [comment]
Afraid not - the data is saved correctly in the database, but the `get_lzb_meta` function is returning incorrect data (because it's looking to the incorrect database attribute) when returning a value for the checkbox/toggle field.

E.g. with the fix I added above, I got the correct data without having to re-save anything to the database.

**Comment by nk-o** [comment]
This is strange because when I tested it, meta returned correctly for controls with default checked value and without default.

Anyway, this code part (https://github.com/nk-o/lazy-blocks/blob/master/src/controls/toggle/index.php#L87-L108) will be removed in the coming plugin update and your issue should be resolved.

This code part was as a workaround for default meta values. Since WordPress 5.5 we can define a default value for meta using official API and our hack no more needed.

**Comment by edwinwills** [comment]
Ah got it - thanks for the help, I'll leave my fix in for now until the update.
