### ISSUE TITLE
Call functions or pass data to blocks from post context - question

### ISSUE THREAD

**Issue by danillolima** [nk-o/lazy-blocks#186]
Hello guys, 
I'm trying make a query that the data need to be queried from db one time, when open the post, but I need share this data with all the blocks of post. I'm making this saving the data from the post in a meta key, then calling in each block, but this is not a inefficient approach? Then I like to know if have a solution that I haven't seen.

**Comment by nk-o** [comment]
Hey.

In the editor, each block requested separately using AJAX. And there is no possibility to make a context for such a rendering method.

In the frontend, you can use any possible way to provide context. The easiest way - is using global PHP variables, but your way with meta data will also work. I don't know which method is the best, you will need to determine it by yourself.

Regards, nK.
