### ISSUE TITLE
Image block error 

### ISSUE THREAD

**Issue by pharmarin** [nk-o/lazy-blocks#21]
Error when adding image in block : `undefined is not an object (evaluating 'h.length')` where h = allowedTypes in https://github.com/WordPress/gutenberg/blob/27b15298656576e0d83e9603555f3f62db7ad5ac/packages/editor/src/components/media-placeholder/index.js#L145

**Comment by nk-o** [comment]
It was fixed in 1.2.1. Have you checked it?

**Comment by pharmarin** [comment]
Yes It works well, thanks !

**Comment by AdsonCicilioti** [comment]
@pharmarin, Close this if already solved!
Nice wirk @nk-o
