### ISSUE TITLE
srcset in image block

### ISSUE THREAD

**Issue by mosne** [nk-o/lazy-blocks#22]
Hi can you add the srcset attribute to the image block please?
`$srcset = wp_get_attachment_image_srcset( $image["id"], $size , true);`
personally I use lazy loading plugin so having the width, height, and ratio of an image would be a big plus! 
thank you for this amazing plugin, I'm looking forward use it in my next project!

**Comment by mosne** [comment]
thank you it works just great!
here the code (that can be helpful as example for others)
`if ( function_exists( 'lazyblocks' ) ) :


/**
     * Test Render Callback
     *
     * @param array $attributes - block attributes.
     */

       function lazyblock_test_render_callback( $attributes ) {
        
        $image=($attributes['image']); //print_r($image);
        $srcset = wp_get_attachment_image_srcset( $image["id"], "medium" , true);
    
        if ($srcset==""){
            $srcset=  $image["url"]." 320w";
        }

        echo '<div class="wrapper">
                <img class="lazyload" src="'.$image["url"].'" sizes="auto" srcset="'.$srcset.'" alt="'.$image["alt"].'"/>
              </div>';
        
    }
    
/**
* Add Block
*/


lazyblocks()->add_block( array(
    'id' => 1944,
    'title' => 'm_image',
    'icon' => 'dashicons dashicons-format-image',
    'keywords' => array(
    ),
    'slug' => 'lazyblock/mimage',
    'description' => 'Image',
    'category' => 'common',
    'category_label' => 'common',
    'supports' => array(
        'customClassName' => true,
        'anchor' => false,
        'align' => array(
            0 => 'wide',
            1 => 'full',
        ),
        'html' => false,
        'multiple' => true,
        'inserter' => true,
    ),
    'controls' => array(
        'control_de2b444521' => array(
            'sort' => '',
            'child_of' => '',
            'label' => 'image',
            'name' => 'image',
            'type' => 'image',
            'min' => '',
            'max' => '',
            'step' => '',
            'date_time_picker' => 'date_time',
            'multiline' => 'false',
            'default' => '',
            'checked' => 'false',
            'placement' => 'inspector',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
        ),
    ),
    'code' => array(
        'editor_html' => '<img src="{{image.url}}" alt="{{image.alt}}"/>',
        'editor_css' => '',
        'frontend_callback' => 'lazyblock_test_render_callback',
        //'frontend_html' => 'custom',
        //'frontend_css' => '',
    ),
    'condition' => array(
    ),
) );

endif;`

**Comment by nk-o** [comment]
Added title in image object, but you need to resave post to get it.

btw, you can use `wp_get_attachment_image` function, it adds srcset and sizes attributes automatically.

```php
function lazyblock_test_render_callback( $attributes ) {
    ob_start();

    ?>

    <div class="my-image">
        <?php echo wp_get_attachment_image( $attributes['image']['id'], 'large' ); ?>
    </div>

    <?php

    return ob_get_clean();
}
```

**Comment by pixeldesignstudio** [comment]
Is it possible to add this feature the "easy" way.
It would be great if there is an dropdown in the "CONTROL" field of "type: image" where you can choose the different image sizes. 
Creating extra functions makes everything complicated again. 

Thx!

**Comment by nk-o** [comment]
Since added php output method, users may use all WordPress functions inside constructor.
