### ISSUE TITLE
Bug? Template no actions

### ISSUE THREAD

**Issue by AdsonCicilioti** [nk-o/lazy-blocks#24]
![image](https://user-images.githubusercontent.com/6278398/48885951-35d7f400-ee11-11e8-90b6-458b3b732455.png)

I created one template test and now dont exists any actions for this item. What happened?

I can't do nothing.. delete, edit...

**Comment by nk-o** [comment]
Yep, fixed in https://github.com/nk-o/lazy-blocks/commit/450272bef59e6f9c69f94fda7486dd40b610180b. Soon plugin will be updated.

**Comment by AdsonCicilioti** [comment]
Hi @nk-o 

Now, the template list not visible and browser console reports this error:
![image](https://user-images.githubusercontent.com/6278398/48974439-b6306c00-f040-11e8-85db-8492454a1fa9.png)

**Comment by nk-o** [comment]
Do you still see this error? It is working fine for me with the latest Gutenberg and Lazy Blocks.

**Comment by AdsonCicilioti** [comment]
It is in the Local Machine phase (PHP 7.2 + MariaDb) and in the production environment (PHP 5.6 + Apache + MariaDB), both with latest versions of Wordpress / Gutenberg / LazyBlocks.
![untitled-1](https://user-images.githubusercontent.com/6278398/49484223-61011100-f81d-11e8-9399-7089b8ba467a.gif)

**Comment by nk-o** [comment]
Maybe conflicted with some of the plugins or with the theme? Please, try to disable it one by one and check if the error still exists.

**Comment by AdsonCicilioti** [comment]
![image](https://user-images.githubusercontent.com/6278398/49551947-84d55d00-f8d8-11e8-800a-ba4e24bcfeda.png)

All plugins disable - except Lazy Blocks and Gutenberg, Twenty Seventen theme enabled.

**Comment by AdsonCicilioti** [comment]
When I disable Gutenberg the error disappears, and the "test" template I created in the previous version of Lazy Blocks looks like this:

![image](https://user-images.githubusercontent.com/6278398/49552187-9bc87f00-f8d9-11e8-9338-e9e357e7b461.png)

Can the fact that this template have been created in the previous version generate some kind of conflict?
And I still do not see any control fields (edit, to trash, etc)

**Comment by nk-o** [comment]
Yes, maybe something broken in the previously generated templates.

I may try to look at it by myself, but I need admin access to your site. Please, create a private ticket here if you okay with giving me a temporary access https://nk.ticksy.com/

**Comment by nk-o** [comment]
Since I can't repeat this bug, I hope it will be finally fixed after this commit https://github.com/nk-o/lazy-blocks/commit/f5e1775258181c591deaeffb117fad87a7ae87d3 (Templates page moved to React)
