### ISSUE TITLE
Issue on Img

### ISSUE THREAD

**Issue by julianbianqui** [nk-o/lazy-blocks#25]
Hi! I am using the latest version in of your plugin, but I have problem with the field type img, here is my setting:
![descarga 1](https://user-images.githubusercontent.com/39094745/48912978-e23bc980-ee55-11e8-9e86-f92a6694ccde.png)

I am placing this code in my functions.php

```
function getlistatemplate( $atts ) {
	var_dump($atts);
	return $atts;
}
add_shortcode( 'shortcode_lista_template', 'getlistatemplate' );
```
This is what is shown in frontend
array(3) { ["classname"]=> string(0) "" ["align"]=> string(0) "" ["anchor"]=> string(0) "" } 
Best!

**Comment by nk-o** [comment]
In coming update it will be fixed. Image control will return string with json data in do_shortcode. You can use it in this way:

```php
function getlistatemplate( $atts ) {
	$img_data = json_decode( $atts['lista_img'], true );

	var_dump($img_data);

	return 'content';
}
add_shortcode( 'shortcode_lista_template', 'getlistatemplate' );
```

**Comment by jnschrag** [comment]
This is an old issue, but if anyone else comes across this and is having trouble accessing the information about the image, you might need to do this:

```php
$image_data = json_decode( html_entity_decode($atts['image'] ), true);
```

I'm not sure what was causing it, but without the `html_entity_decodes`, I could not successfully use `json_decode` due to a syntax error.
