### ISSUE TITLE
Custom PHP code for render in Editor

### ISSUE THREAD

**Issue by AdsonCicilioti** [nk-o/lazy-blocks#27]
Is it allowed to pass a custom code function to be rendered in the editor just as it is passed to FrontEnd?

Please. If this is possible explain to me how. If it is still not allowed, could you implement this functionality?

That would make Lazy Blocks even better. Thx!

Refered in:
https://wordpress.org/support/topic/php-code-for-render-in-editor/

**Comment by AdsonCicilioti** [comment]
I can pass a function to editor_callback like as frontend_callback?

**Comment by nk-o** [comment]
Yep, PHP code for both frontend and editor output in plans as an alternative to Handlebars, but no free time yet.

Custom output callback available only for frontend yet.

p.s. if someone may help with this, Pull Requests are welcome https://github.com/nk-o/lazy-blocks/pulls
