### ISSUE TITLE
Feature Request: Output control values on Inner Blocks wrapper 

### ISSUE THREAD

**Issue by AdsonCicilioti** [nk-o/lazy-blocks#31]
I need to show in the editor the application of the values of other controls in an element that wraps the drag zone of the Inner Block. Look.
![image](https://user-images.githubusercontent.com/6278398/49693238-6bd8e000-fb54-11e8-9826-28041dd0b0c2.png)
> Note: I am aware that it is unnecessary to use the {{{inner_block}}} output in the HTML Editor.

In the editor I have the div set to HTML Editor, appearing below the drop zone and receiving the values of the color fields.
![image](https://user-images.githubusercontent.com/6278398/49693278-7ba4f400-fb55-11e8-9910-cfe98d6e4038.png)

In forntend this all right:
![image](https://user-images.githubusercontent.com/6278398/49693281-937c7800-fb55-11e8-98cf-c3f5fd5ef499.png)

So I think this kind of control deserves a field to get out of the values of the fields in your wrapper. Thus, we give the editor User an adequate experience.

What do you think?

**Comment by nk-o** [comment]
I think will be better to let users possibility to change styles of the block in editor. First we need to add unique IDs to blocks (https://github.com/nk-o/lazy-blocks/issues/32) and then will be possible to add styles by inline &lt;style&gt; tag.

Something like this (Editor HTML):

```html
<style>
.my-block-{{block_id}} {
    background-color: {{bg_color}};
    color: {{color}};
}
</style>
```

**Comment by AdsonCicilioti** [comment]
Yep! That would solve.

**Comment by LukeFlego** [comment]
I'm using custom PHP where I add `className` to an inner element after creating my own custom wrap. However as of [v1.4.0](https://github.com/nk-o/lazy-blocks/releases/tag/v1.4.0), the newly added `div` breaks the layout.

Would be great to only force the wrap if `className` is not manually used in Handlebars/PHP.

**Comment by nk-o** [comment]
Hi @LukeFlego.

Could you give me an example where the layout was broken? Also added a reply to the user with the same issue https://wordpress.org/support/topic/new-version-has-messed-things-up-for-me/#post-11136645.

**Comment by LukeFlego** [comment]
@nk-o You are a legend.

It was just a personal break, where I had relied on an element being a direct child. Adding the `div` between broke that.

Eg, the following CSS
```css
.parent > .my-lazy-block {...}
```
and HTML
```html
<div class="parent">
  <div class="my-lazy-block"> <!-- Does match 👍 -->
    Lorem ipsum dolar si...
  </div>
</div>
```
HTML with wrapper
```html
<div class="parent">
  <div class="wrapper">
    <div class="my-lazy-block"> <!-- Doesn't match 👎 -->
      Lorem ipsum dolar si...
    </div>
  </div>
</div>
```
