### ISSUE TITLE
Inner blocks in php render callback

### ISSUE THREAD

**Issue by pharmarin** [nk-o/lazy-blocks#35]
In the render callback, $attributes for innerBlock are empty even if innerBlock is present. 
Should return the innerBlock object instead.

**Comment by nk-o** [comment]
Could you give some more information, so I can repeat the bug?

It is working fine for me:

1. Lazy block created:
	![image](https://user-images.githubusercontent.com/14810891/51429835-0b918f80-1c24-11e9-9af3-c3b0ecea7922.png)

2. Added output PHP filter:
	![image](https://user-images.githubusercontent.com/14810891/51429843-2fed6c00-1c24-11e9-8b5e-74f18308ca34.png)

3. Added block in the post and inserted inner block:
	![image](https://user-images.githubusercontent.com/14810891/51429856-4dbad100-1c24-11e9-9804-b8b5f1f174f9.png)

4. The result on frontend:
	![image](https://user-images.githubusercontent.com/14810891/51429882-91153f80-1c24-11e9-988c-3e456ae91ba5.png)

**Comment by pharmarin** [comment]
My fault, made a stupid mistake.
