### ISSUE TITLE
default handlebars log helper

### ISSUE THREAD

**Issue by iannacone** [nk-o/lazy-blocks#41]
As related here:
[https://lazyblocks.com/documentation/blocks-code/handlebars/](https://lazyblocks.com/documentation/blocks-code/handlebars/)
> Output HTML support Handlebars syntax

but when i try to log via the output with `{{log "Log!" level="error"}}` i get this error message:
> Fatal error: Uncaught InvalidArgumentException: Variable name is invalid: "log "Log!" level="error"" in ...

**Comment by iannacone** [comment]
handlebars.php commit[](https://github.com/XaminProject/handlebars.php/commit/42fb27e0501d41eb47220baa4e14347185ccd23e)

**Comment by nk-o** [comment]
Hi.

If this will be implemented in Handlebars PHP library, it will be updated in the plugin code. For now I can add WP filter, so developers will be able to add any custom Helpers.

**Comment by iannacone** [comment]
what will change in the new version without js handlebars?
honestly i didn't notice that there was js handlebars (only php handlebars)

**Comment by nk-o** [comment]
Seems like you started using Lazy Blocks since 1.4.0 version? :)
JS Handlebars was removed in this update. Full changelog you can find here - https://wordpress.org/plugins/lazy-blocks/#developers

**Comment by iannacone** [comment]
right :-)

**Comment by nk-o** [comment]
You can try to add custom helpers https://lazyblocks.com/documentation/blocks-code/handlebars/#custom-helpers
