### ISSUE TITLE
PHP Front-End render

### ISSUE THREAD

**Issue by tjc042** [nk-o/lazy-blocks#43]
I'm very new to both word press and PHP development so forgive me but I am trying to get PHP to render on my front end as an alternative to HTML. Tried using the documentation but can't seem to get it figured out.  

I have added the code into the frontend HTML editor:
```
<?php
// filter for Frontend output.
add_filter( 'lazyblock/testing1234/frontend_callback', 'my_block_output');

if ( ! function_exists( 'my_block_output' ) ) :
    /**
     * Test Render Callback
     *
     * @param string $output - block output.
     * @param array  $attributes - block attributes.
     */
    function my_block_output( $output, $attributes ) {
        ob_start();
        ?>

        <div>
            Control value: <?php echo "My Test Code"; ?>
        </div>

        <?php
        return ob_get_clean();
    }
endif;
```
Simply trying to get the example to work but I'm clearly missing something.  I have checked that in fact my slug name is "testing1234".  Do I need to store a .php somewhere else or update my function.php file somehow.  Any help would be greatly appreciated.  Thanks!

**Comment by nk-o** [comment]
Hi.

You did everything right, no additional PHP file is needed anywhere. Seems like rendering bug in the plugin. Will be fixed in the coming update.

Related issue https://github.com/nk-o/lazy-blocks/issues/42

**Comment by tjc042** [comment]
Thanks for the quick reply. Any idea when the next update will be released?

**Comment by tjc042** [comment]
Also, I tried adding in the Content as well using a "control" with the same name as that given in the sample but it didn't show any impact.  Thanks!
