### ISSUE TITLE
PHP 7.3 continue switch warnings

### ISSUE THREAD

**Issue by rebeccahum** [nk-o/lazy-blocks#44]
Hi there,

The below lines throw PHP 7.3 warnings:

https://github.com/nk-o/lazy-blocks/blob/97a5ab6c7e294ec1e77a0507d1b1e3276510f558/src/vendor/Handlebars/Tokenizer.php#L167

https://github.com/nk-o/lazy-blocks/blob/97a5ab6c7e294ec1e77a0507d1b1e3276510f558/src/vendor/Handlebars/Tokenizer.php#L213

```
continue statements targeting switch control flow structures will now generate a warning. In PHP such continue statements are equivalent to break, while they behave as continue 2 in other languages.
```

http://php.net/manual/en/migration73.incompatible.php#migration73.incompatible.core.continue-targeting-switch

Unfortunately, the handlebars library is no longer being supported: https://github.com/XaminProject/handlebars.php

**Comment by rebeccahum** [comment]
@nk-o Hi! Can this be looked into?

**Comment by nk-o** [comment]
Hi @rebeccahum.

Thank you for the info, I'll check it before coming update.

**Comment by rebeccahum** [comment]
@nk-o Great! Any idea when we can get this merged?

**Comment by oyatek** [comment]
replace `continue` with `continue 2`.
