### ISSUE TITLE
Select control not working

### ISSUE THREAD

**Issue by julio-hachette** [nk-o/lazy-blocks#45]
It doesn't save the values added in choices

**Comment by nk-o** [comment]
Maybe you can give some more info?

1. Editor:
	![image](https://user-images.githubusercontent.com/14810891/52109435-8e482080-260e-11e9-966e-45c65100311f.png)
2. Frontend:
	![image](https://user-images.githubusercontent.com/14810891/52109462-a1f38700-260e-11e9-9045-3ee0e32a551e.png)
