### ISSUE TITLE
lzb_handlebars_object action

### ISSUE THREAD

**Issue by iannacone** [nk-o/lazy-blocks#46]
the action lzb_handlebars_object it seems not working.
i tried to add in my `functions.php` theme file the following code:
`function my_custom_lazyblock_handlebars_helper ( $handlebars ) {`
`exit('register'); // it does not anything because i get the error before that`
`    $handlebars->registerHelper( 'my_test_helper', function( $val ) {`
`        return '<p>My test helper: ' . $val . '</p>';`
`    } );`
`}`
add_action( 'lzb_handlebars_object', 'my_custom_lazyblock_handlebars_helper' );`

but i get:
`Fatal error: Uncaught RuntimeException: "my_test_helper"" is not registered as a helper in /[...]/wp-content/plugins/lazy-blocks/vendor/Handlebars/Template.php:497`
`Stack trace:`
`#0 /[...]/wp-content/plugins/lazy-blocks/vendor/Handlebars/Template.php(240): Handlebars\Template->_section(Object(Handlebars\Context), Array)`
`#1 /[...]/wp-content/plugins/lazy-blocks/vendor/Handlebars/Template.php(187): Handlebars\Template->renderInternal(Array, Object(Handlebars\Context))`
`#2 /[...]/wp-content/plugins/lazy-blocks/vendor/Handlebars/Handlebars.php(210): Handlebars\Template->render(Object(Handlebars\Context))`
`#3 /[...]/wp-content/plugins/lazy-blocks/classes/class-blocks.php(1352): Handlebars\Handlebars->render('<div class="tes...', Array)`
`#4 /[...]/wp-includes/class-wp-block-type.php(109): LazyBlocks_Blocks->render_callback(Array, '')`
`#5 /[...]/wp-includes/blocks.php(193): WP_Block_Type->render(Array, '')`
`#6 /[...]/wp-content/plugins/lazy-blocks/vendor/Handlebars/Template.php on line 497`

it seems that the helper action is called too late

**Comment by iannacone** [comment]
should i wrote:
`{{my_test_helper 'test value'}}`
from [doc](https://lazyblocks.com/documentation/blocks-code/handlebars/)

or
`{{#my_test_helper 'test value'}}`
---^
from [doc](http://handlebarsjs.com/block_helpers.html)

**Comment by iannacone** [comment]
i solved calling again `LazyBlocks_Blocks.prepare_handlebars()` after my `add_action` in `functions.php`:

`$lazyblocks = LazyBlocks::instance();`
`$lazyblocks_blocks = $lazyblocks->blocks();`
`$lazyblocks_blocks->prepare_handlebars();`

i read the code (well done) basically you initialize the main class LazyBlocks to the action plugins_loaded. this doesn't let the time to register my actions in the theme which is called after.
you can use after_setup_theme, init (most used) or wp_loaded.
[https://codex.wordpress.org/Plugin_API/Action_Reference/plugins_loaded](https://codex.wordpress.org/Plugin_API/Action_Reference/plugins_loaded)

**Comment by iannacone** [comment]
i tried the other hooks, but it does not work anyway

**Comment by nk-o** [comment]
Hi.

Thank you for info, will be fixed in the next update.
