### ISSUE TITLE
Disable Inner Blocks in Repeater

### ISSUE THREAD

**Issue by iannacone** [nk-o/lazy-blocks#47]
Inner Blocks does not work as expected in the Repeater field.
**Until** there is no option to use more than one Inner Blocks as fields, i recommend to disable the Inner Blocks in the Repeater.

**Comment by nk-o** [comment]
Seems like a bug after first add control. After publish it is hidden.

**Comment by kiaramelissa** [comment]
I was just wondering what the progress is on this?
I can add the Inner Block to a Repeater field but disappears after publish, and is unable to be used.
Would love to be able to use Inner Blocks in repeater, then Lazy Blocks will be absolutely PERFECT!

**Comment by nk-o** [comment]
@kiaramelissa it is not possible to use InnerBlocks inside the repeater. Gutenberg supports only 1 InnerBlocks component per block.

**Comment by iannacone** [comment]
Not really: what about the columns block?

**Comment by nk-o** [comment]
@iannacone Columns block uses a single InnerBlocks component with an additional attribute. Look at the source code in the Gutenberg repository.

**Comment by iannacone** [comment]
The problem comes again with the new version
