### ISSUE TITLE
Rich text editor - can't use html tags

### ISSUE THREAD

**Issue by lucastoma** [nk-o/lazy-blocks#48]
When adding new line or any other tag in back end it is converted to text representation of tag like in code editor or sth like that.

**Comment by nk-o** [comment]
Make sure you output it properly https://lazyblocks.com/documentation/blocks-controls/rich-text-wysiwyg/

**Comment by kiaramelissa** [comment]
I have the same issue... I have used the three handlebars to output the block control properly, but when i paste any html the code just shows up as text
