### ISSUE TITLE
Working with meta and multiple blocks

### ISSUE THREAD

**Issue by moisespio** [nk-o/lazy-blocks#50]
I have a block that can be reused in the same page/post. However, I didn't find a way to use the meta feature, because when I have multiple blocks, these blocks controls will have the same meta.

Here's an example:

```
Block Name: Content

Controls:
- Title (meta: content-title)
- Subtitle (meta: content-subtitle)
```

```
Page: Home

Blocks:
- Content
-- Title: This is the title
-- Subtitle: This is the subtitle
- Content
-- Title: This is the second title
-- Subtitle: This is the second subtitle
```

**Comment by nk-o** [comment]
In these blocks value saved not in the blocks directly, but in the metadata of the post. So, if you add 2 blocks with the same meta, value in it will be the same.

Official documentation for Meta blocks https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/metabox/meta-block-3-add/
