### ISSUE TITLE
No action when selecting Templates

### ISSUE THREAD

**Issue by thueske** [nk-o/lazy-blocks#51]
Hey,

I would like to add an Template, but when clicking the site reloads but remains empty.

- Tobias
![bildschirmfoto 2019-02-11 um 14 31 12](https://user-images.githubusercontent.com/436986/52566384-eac6ef00-2e09-11e9-9ca3-a649fe81f77f.png)

**Comment by nk-o** [comment]
fixed in https://github.com/nk-o/lazy-blocks/commit/7ec586457cb9d4a94a5ce84ec62c1ba05c8f4f05
