### ISSUE TITLE
Repeater index in handlebar

### ISSUE THREAD

**Issue by biswajit-paul** [nk-o/lazy-blocks#52]
We are trying to build bootstrap v3.3.7 accordion. It required dynamic div ID and anchor href value. 
https://getbootstrap.com/docs/3.3/javascript/#collapse-example-accordion. Can we get repeater index in handlebar? Like below:

```
{{#each index in control_name}}
  <p>{{inner_control_name}}</p>
{{/each}}
```

**Comment by nk-o** [comment]
Try this one:

```html
{{#each control_name}}
  <p>{{@index}}: {{inner_control_name}}</p>
{{/each}}
```

**Comment by biswajit-paul** [comment]
@nk-o Many many thanks
