### ISSUE TITLE
not working or showing in blocks menu

### ISSUE THREAD

**Issue by devmondo** [nk-o/lazy-blocks#56]
HI, 
what an amazing work and solution,  i really want to thank you for this. 

but i have a problem, i created a simple test block, same as instructed in the docs, but it is not showing in the Gutenberg blocks menu under any category. no erros or anything. just not showing.

i am using WordPress 5.1

thanks in advanced.

**Comment by nk-o** [comment]
Hi.

Maybe you didn't set Category or something. Could you show me a screenshot from the block constructor page?

**Comment by devmondo** [comment]
thanks a lot for the reply, 
i did add it, even if i add it to lazyblocks category or any other category, nothing shows up.

![image](https://user-images.githubusercontent.com/1266367/53697137-a5358a80-3de7-11e9-9660-3b9cc23d5e97.png)
![image](https://user-images.githubusercontent.com/1266367/53697139-a9fa3e80-3de7-11e9-89bc-0d3c4fcf33bc.png)

**Comment by nk-o** [comment]
I still can't repeat this bug.

Maybe there is a conflict with some of the 3rd-party plugins. Try to deactivate plugins one by one, so we can find which one is conflicted.

Also make sure that `Inserter` setting is checked:

![image](https://user-images.githubusercontent.com/14810891/54812962-72234000-4c9d-11e9-80bd-6bcff13135ca.png)

**Comment by devmondo** [comment]
@nk-o 
thanks a lot for the feedback, and indeed i installed it on a fresh wordpress installation and it is working perfectly. 

so it must be a conflict with some plugin, but i am not able to pin it out, as i tried to disable all plugins and yet it is not working, maybe one of those plugins corrupted the DB or changed something?  but i confirm it is working on a fresh install, so i will go ahead and close this issue for now to not pollute your repo and reopen it if something comes up.


really an awesome idea and work, thanks again for making this plugin :)

**Comment by nk-o** [comment]
If you disabled all plugins and Lazy Blocks still doesn't show up, most probably it is our plugin bug.

No problem, open this issue if you will see the same bug again.
