### ISSUE TITLE
Wysiwyg more toolbar buttons

### ISSUE THREAD

**Issue by nk-o** [nk-o/lazy-blocks#57]
Related topic: https://wordpress.org/support/topic/super-helpful-block-creation-tool/

**Comment by manuel-84** [comment]
It would be nice also if we can use Markdown syntax inside wysywig and/or as a specific control type

**Comment by Sybio** [comment]
Any news about this issue :D ?

Could be great to allow overriding a function and set controls for the rich textarea.

**Comment by nk-o** [comment]
@Sybio I'll check it, but no promise that a solution will be added to resolve the issue. Currently working on a big plugin update :)

**Comment by nk-o** [comment]
Hey guys.

Since v2.0 plugin update will be available new control named Classic Editor. This is a classic TinyMCE editor, which was used before WordPress Gutenberg released. https://lazyblocks.com/documentation/blocks-controls/classic-editor-wysiwyg/

So, all the plugin extensions for this editor should also work for this Lazy Blocks control.

What about Gutenberg Rich Text control. You may extend it using these examples - https://developer.wordpress.org/block-editor/tutorials/format-api/2-toolbar-button/
