### ISSUE TITLE
Anchor is not saving

### ISSUE THREAD

**Issue by nk-o** [nk-o/lazy-blocks#58]
Related topic: https://wordpress.org/support/topic/html-anchor-not-saving/

**Comment by pixeldesignstudio** [comment]
Any news on this bug?

**Comment by nk-o** [comment]
Related topic https://wordpress.org/support/topic/anchors-do-not-work/

Found, that the problem in older Gutenberg version and configuration in Lazy Blocks plugin (fixed in https://github.com/nk-o/lazy-blocks/commit/7236d11a5f8c0095c218878c7889ba70a8807530).

**Comment by manuel-84** [comment]
Still not saving in 1.6.2
