### ISSUE TITLE
Echo custom PHP or theme directory in code block

### ISSUE THREAD

**Issue by nabtron** [nk-o/lazy-blocks#62]
Hi.

I need to output an image with the block. However I can't find a way to get the theme directory url in the frontend html block. 

Can you guide please?

**Comment by nk-o** [comment]
Hi.

You can use filters to output code: https://lazyblocks.com/documentation/blocks-code/php/

Lazy Blocks has never worked with the theme directory. I don't think it will be implemented in future updates. PHP code editor will be added later in the block constructor.

Regards, nK.
