### ISSUE TITLE
[request] custom control integration

### ISSUE THREAD

**Issue by sandromattei** [nk-o/lazy-blocks#63]
Hi!
Possibility to integrate api to add custom control?

**Comment by nk-o** [comment]
Hi.

I think it is a good suggestion, but not for the current plugin code. We need first move admin pages to Gutenberg and React. https://github.com/nk-o/lazy-blocks/issues/38

**Comment by nk-o** [comment]
API for custom controls will be added to Lazy Blocks v2.0.0

Documentation https://lazyblocks.com/documentation/examples/create-custom-control/
Custom Control Template https://github.com/nk-o/lazy-blocks-custom-control-template
