### ISSUE TITLE
Image Control Error - Renders as 'Array'

### ISSUE THREAD

**Issue by dancollings** [nk-o/lazy-blocks#67]
Hi - I've ran into an issue. Latest version is throwing an error printing an image in the Front-end and Editor code. Other control types are fine but image only prints 'Array'. Could anyone help me find out why that's happening?

<img width="487" alt="Screen Shot 2019-03-25 at 20 12 48" src="https://user-images.githubusercontent.com/48928136/54950819-0d384600-4f3a-11e9-9863-7b2160f70e7c.png">
<img width="959" alt="Screen Shot 2019-03-25 at 20 12 27" src="https://user-images.githubusercontent.com/48928136/54950820-0d384600-4f3a-11e9-8b6f-68e66f8c057f.png">

**Comment by matt3224** [comment]
Hey,

You'll need to do `image_right.url` judging by the docs

**Comment by dancollings** [comment]
Thanks @matt3224 - much appreciated!
