### ISSUE TITLE
Triple handlebars to output inner_block content in editor

### ISSUE THREAD

**Issue by paulkirspuu** [nk-o/lazy-blocks#69]
Is it possible to output `inner_block` content in editor html? Tried using it same way as instructed here, https://lazyblocks.com/documentation/blocks-controls/inner-blocks/, unfortunately without positive results. Same template used in editor html works in front-end html though.

EDIT: also not possible via `Custom meta field usage`, as instructed in the docs.

Is this a known bug, or am I doing it wrong?

**Comment by nk-o** [comment]
No, it is not possible. I apologize for disinformation in the documentation and in blocks constructor interface about meta fields.

This is a related issue, where you may find a possible workaround with styles: https://github.com/nk-o/lazy-blocks/issues/31

**Comment by paulkirspuu** [comment]
@nk-o alright, thanks for the info. What is stopping you and the dev team from adding `inner_block` type block content to query parameters? Other block type values are all there.

**Comment by nk-o** [comment]
@paulkirspuu this is not just a field with the value, this is a separate Gutenberg component, that works with inner blocks and there is no documented way to save the value in meta fields, or send it somewhere, we can only save it as block content.

If someone will have a solution, I want to see it :)

**Comment by paulkirspuu** [comment]
@nk-o I am talking about the editor preview, not sure if that was clear. It is just a value, simple HTML markup to be more exact.

You're currently sending other field value types to query request via POST on each block field change event, could also send this HTML markup of the `inner_block`?
