### ISSUE TITLE
Image output via json

### ISSUE THREAD

**Issue by u12206050** [nk-o/lazy-blocks#74]
When outputting Gutenberg blocks via REST as JSON objects all image fields look like this: `%7B%22alt%22:%22%22,%22title%22:%223%22,%22caption%22:%22%22,%22id%22:55,%22link%22:%22https://new.day4.live/?attachment_id=55%22,%22url%22:%22https://new.day4.live/wp-content/uploads/2019/05/3.jpg%22%7D`  making it quite hard to work with.

Could this be fixed to output an object rather than a url encoded object string?

This is the general code used to get blocks out as json if you don't have it:
```
<?php

add_action(
  'rest_api_init',
  function () {

    if ( ! function_exists( 'use_block_editor_for_post_type' ) ) {
      require ABSPATH . 'wp-admin/includes/post.php';
    }

    // Surface all Gutenberg blocks in the WordPress REST API
    $post_types = get_post_types_by_support( [ 'editor' ] );
    foreach ( $post_types as $post_type ) {
      if ( use_block_editor_for_post_type( $post_type ) ) {
        register_rest_field(
          $post_type,
          'blocks',
          [
            'get_callback' => function ( array $post ) {
              return parse_blocks( $post['content']['raw'] );
            },
          ]
        );
      }
    }
  }
);
```

**Comment by nk-o** [comment]
Currently, we don't have the possibility to save structured data as objects in Gutenberg blocks. It is simply not supported.

**Comment by u12206050** [comment]
Ok, No problem. Thanks.
