### ISSUE TITLE
CPT + Save in meta not saving

### ISSUE THREAD

**Issue by iannacone** [nk-o/lazy-blocks#82]
The controls with the option "Save in meta" activated are not saving in the Custom Post Type editor. They are emptied when i click on the save button (update and publish both).

**Comment by nk-o** [comment]
I need some more info because it is working fine for me.

1. ![image](https://user-images.githubusercontent.com/14810891/60095812-29759a00-9758-11e9-9edf-4481ce46fd7a.png)
2. ![image](https://user-images.githubusercontent.com/14810891/60095863-46aa6880-9758-11e9-8061-b47246f3d97e.png)

p.s. Tested in your Profile CPT

**Comment by iannacone** [comment]
sorry, i notice right now that the meta control is an image. with textbox it works fine.

**Comment by iannacone** [comment]
additionally can we have the possibility to have available the controls for the handlebars context also if it is saved in the meta?

right now i solved it with a helper which take the meta value and inject it in the context:

```
$handlebars->registerHelper('retrieve-meta', function($id, $options = null) {
	$meta = get_lzb_meta($id);
	$options['context']->push([$id => $meta]);
});
```

**Comment by nk-o** [comment]
Also working for me:

![image](https://user-images.githubusercontent.com/14810891/60170871-07d8e900-9812-11e9-9e0e-f61db088a578.png)

I don't think such meta manipulation will be added in the plugin. I recommend you use PHP output for complex code. Handlebars used for simple blocks. In the future updates will be added option to choose Handlebars or PHP editor in blocks constructor.

**Comment by iannacone** [comment]
when i click on the checkbox for showing the custom fields the page reloads and nothing is shown.
on a fresh install it works...

**Comment by iannacone** [comment]
if it can help somewho: [the solution](https://github.com/WordPress/gutenberg/issues/16333#issuecomment-506448303)
