### ISSUE TITLE
Publishing a new lazy-block

### ISSUE THREAD

**Issue by iannacone** [nk-o/lazy-blocks#84]
After publishing a new lazy-block, the update button appears and it seems that never saves because when i try to close the window, the browser ask me if i am sure to close because i can lose my data.

**Comment by iannacone** [comment]
also when updating a lazy-block with a new control.

**Comment by nk-o** [comment]
Should be fixed in https://github.com/nk-o/lazy-blocks/commit/42c606b52bb6160e7a9cabdfbebd77ef3df81dd3

The plugin will be updated soon.
