### ISSUE TITLE
Cannot delete the template

### ISSUE THREAD

**Issue by iannacone** [nk-o/lazy-blocks#85]
after creating a template i am not able to delete it anymore.
to the remove button a xhr starts with a wrong path:
`[...]/index.php?rest_route=/wp/v2/lazyblocks_templates/20?force=true`
which responds with a 404 error.

use instead `window.lazyblocksData.url` or `window.ajaxurl` and please add also the nonce in `window.lazyblocksData.nonce` as parameter for security reason

**Comment by iannacone** [comment]
probably ajaxurl has nothing to do with the xhr request that you are using, right?

**Comment by nk-o** [comment]
For templates saving and removing used default `wp.api.models` call.

Probably this behavior will be changed when this page will be moved to React (https://github.com/nk-o/lazy-blocks/issues/38).
