### ISSUE TITLE
Metabox not updating

### ISSUE THREAD

**Issue by iannacone** [nk-o/lazy-blocks#87]
i have different controls which save the data inside the meta.
they save the value only if the meta is not available (commonly the first time).
but when i try to update an existing meta, it does not do it.
for updating, first i need to delete the meta and then i can update the post.

**Comment by nk-o** [comment]
Do you have enabled "Custom Fields" panel?

I see that block metadata don't save when this panel is enabled. Looks like a Gutenberg bug.

![image](https://user-images.githubusercontent.com/14810891/61270676-08c6c000-a7ab-11e9-83a2-4d301a964178.png)

**Comment by iannacone** [comment]
Yes i had it enabled for debugging purpose

**Comment by nk-o** [comment]
Not related to the plugin code.

**Comment by iannacone** [comment]
By disabling "Custom Fields" option from the panel, it works and updates the value as expected.

If it can help anyone else...
