### ISSUE TITLE
Adding Custom Category

### ISSUE THREAD

**Issue by ravishakya** [nk-o/lazy-blocks#9]
By default, there are few block categories, it would be really great if we can add new block categories.

Reference Link

https://github.com/WordPress/gutenberg/pull/7606
https://github.com/WordPress/gutenberg/issues/8957

**Comment by nk-o** [comment]
You can do this by typing your custom category name and press Enter.

![image](https://user-images.githubusercontent.com/14810891/44903059-38481780-ad14-11e8-8c54-c66877304556.png)
