### ISSUE TITLE
Feature Request: Change titles on "rows" for repeater

### ISSUE THREAD

**Issue by Rice14** [nk-o/lazy-blocks#93]
I'm working on a website that will be managed by many people, and for some, the word "row" is confusing.  It would be great if we were able to change it to match what we were adding.  For example, we often use repeaters for videos, so it would be great to change the word "row" to video.  So instead of this...
<img width="604" alt="Screen Shot 2019-08-15 at 12 39 04 PM" src="https://user-images.githubusercontent.com/5464457/63111036-c683d080-bf5a-11e9-892f-4e80be2b46a9.png">

It would look like this...
<img width="604" alt="add video" src="https://user-images.githubusercontent.com/5464457/63111193-2bd7c180-bf5b-11e9-8c0d-f50acbd289c6.png">

**Comment by kostda** [comment]
And even better would be if i could also choose one of its subields as title and then show it instead of "Row 1".
Something like this:
![image](https://user-images.githubusercontent.com/54975513/64407487-b6a46b80-d084-11e9-85ab-2eec9dc97682.jpg)
