### ISSUE TITLE
Rendering Block Output Custom PHP/HTML

### ISSUE THREAD

**Issue by nhterry** [nk-o/lazy-blocks#96]
Please pardon my ignorance. I am super confused. I am trying to get the custom PHP block code working with a lazy block that I have created through the Wordpress admin.

I cannot figure out how to reference the block I created from the Wordpress admin.

I am referencing documentation here: https://lazyblocks.com/documentation/blocks-code/php/

```
// filter for Frontend output.
add_filter( 'lazyblock/my_block_slug/frontend_callback', 'my_block_output', 10, 2 );
// filter for Editor output.
add_filter( 'lazyblock/my_block_slug/editor_callback', 'my_block_output', 10, 2 );

if ( ! function_exists( 'my_block_output' ) ) :
   function my_block_output( $output, $attributes ) {
        ob_start();
        ?>
        <div>
            Control value: <?php echo esc_html( $attributes['test_control'] ); ?>
        </div>

        <?php
        return ob_get_clean();
    }
endif;
```
I figure I should be able to put this into my functions.php and then change the "my_block_output" to the name of my block (lowercase) with underscores in between words, but it is not working. Or how do I reference the block I created through the Wordpress Admin > Lazyblocks.

Does this code only work if you created the lazy block through PHP to begin with and then reference the custom output callback function?

Thanks!

**Comment by nk-o** [comment]
You need to put your block name in the filter name:

```php
// filter for Frontend output.
add_filter( 'lazyblock/my_block_slug/frontend_callback', 'my_block_output', 10, 2 );

// filter for Editor output.
add_filter( 'lazyblock/my_block_slug/editor_callback', 'my_block_output', 10, 2 );
```

Replace `my_block_slug` to your block name.

And function name `my_block_output` you also need to change to something unique to prevent conflicts.
