### ISSUE TITLE
Feature request: insert hook to onControlChange

### ISSUE THREAD

**Issue by flameoftheforest** [nk-o/lazy-blocks#99]
Hi,

First of all, thank you very much for LazyBlocks, it really helped us to build stuff at speed.

Believe in /src/assets/js/index.jsx, under onControlChange, a 
```
val = applyFilters('lazyblocks-control-change', val, {
                control, childIndex
            });
```
should be added.

This will allow us downstreamers to engage the values updated.

Thanks!

**Comment by nk-o** [comment]
Hi.

Why do you need this filter? Maybe just use React HOC and change attributes when `componentDidUpdate` fires?

**Comment by nk-o** [comment]
https://lazyblocks.com/documentation/js-filters/lzb-editor-control-updatevalue/
